---
title: "p8105_hw6_jw4489"
output: github_document
date: "2023-12-02"
---

```{r, message = FALSE}
library(tidyverse)
library(purrr)
library(modelr)
library(dplyr)
library(broom)
library(ggplot2)
```

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE)
```

## Problem 1

```{r}
homicide = read.csv("hw6data/homicide-data.csv")
view(homicide)
```

##### Load and clean data

```{r}
df1 = homicide |>
  janitor::clean_names() |> 
  mutate(city_state = paste(city, state, sep = ", ")) |>
  mutate(solved = ifelse(disposition == "Closed by arrest", 1, 0)) |>
  filter(!(city %in% c("Dallas", "Phoenix", "Kansas City", "Tulsa"))) |>
  filter(victim_race == "White" | victim_race == "Black") |>
  mutate(victim_age = as.numeric(victim_age))

view(df1)  
```

##### Baltimore model

```{r}
baltimore_df = na.omit(df1) |>
   filter(city_state == "Baltimore, MD")
```

```{r}
baltimore_model = 
  glm(disposition == "Closed by arrest" ~ victim_age + victim_sex + victim_race, 
                      data = baltimore_df, family = binomial)
```

```{r}
baltimore_results = baltimore_model |>
  broom::tidy() |>
  filter(term == "victim_sexMale") |>
  mutate(estimate_or = exp(estimate), 
         CI_lower = exp(estimate - 1.96 * std.error),
         CI_upper = exp(estimate + 1.96 * std.error)) |>
  knitr::kable()      

baltimore_results
```

##### Each city

```{r}
city_results = df1 |>
  nest(data = -city_state) |>
  mutate(models = map(data, \(df) glm(solved ~ victim_age + victim_sex + victim_race, data = df, family = binomial())),
         results = map(models, broom::tidy)) |> 
  select(-models) |> 
  unnest(results) |>
  filter(term == "victim_sexMale") |>
  mutate(estimate_or = exp(estimate),
         CI_lower = exp(estimate - 1.96 * std.error),
         CI_upper = exp(estimate + 1.96 * std.error)) |>
  select(city_state, term, estimate_or, CI_lower, CI_upper)

city_results
```
  
##### Plots

```{r}
results_plot = city_results |>
  mutate(city_state = fct_reorder(city_state, estimate_or)) |> 
  ggplot(aes(x = city_state,y = estimate_or)) + 
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = CI_lower,ymax = CI_upper)) + 
  labs(x = "City", y = "Adjusted Odds Ratio (Male vs. Female)",
       title = "Adjusted Odds Ratios for Solving Homicides (Male vs. Female) by City") +
  theme(axis.text.x = element_text(size = 5, angle = 45, hjust = 1))

results_plot
```

## Problem 2

##### Load data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

##### Bootstrap function

```{r}
bootstrap_regression = function(data) {
  boot_sample = sample_n(data, nrow(data), replace = TRUE)
  model = lm(tmax ~ tmin + prcp, data = boot_sample)
  r_squared = broom::glance(model)$r.squared
  coefficients = broom::tidy(model) |>
    filter(term %in% c("tmin", "prcp")) |>
    summarise(log_beta_product = log(prod(estimate)))
  
  return(c(r_squared, coefficients))
}
```

##### Estimates of 5000 samples

```{r}
bootstrap_results <- data.frame(
  r_squared = numeric(5000),
  log_beta_product = numeric(5000)
)

set.seed(1) 
for (i in 1 : 5000) {
  bootstrap_results[i, ] <- bootstrap_regression(weather_df)
}
```

##### Visualizations

```{r}
ggplot(bootstrap_results, aes(x = r_squared)) +
  geom_histogram() +
  labs(x = "Bootstrap Estimates of r^2", y = "Frequency")

ggplot(bootstrap_results, aes(x = log_beta_product)) +
  geom_histogram() +
  labs(x = "Bootstrap Estimates of log(β1*β2)", y = "Frequency")
```

##### Confidence Interval

```{r}
quantile_0.025_1 = bootstrap_results |>
  pull(r_squared)|>
  quantile(0.025)

quantile_0.975_1 = bootstrap_results |>
  pull(r_squared)|>
  quantile(0.975)

quantile_0.025_1
quantile_0.975_1
```

According to the results above, the 95% confidence interval for r_squared is (`r quantile_0.025_1`, `r quantile_0.975_1`).

```{r}
quantile_0.025_2 = bootstrap_results |>
  pull(log_beta_product)|>
  na.omit()|>
  quantile(0.025)

quantile_0.975_2 = bootstrap_results |>
  pull(log_beta_product)|>
  na.omit()|>
  quantile(0.975)

quantile_0.025_2
quantile_0.975_2
```

According to the results above, the 95% confidence interval for og(β̂ 0∗β̂ 1) is (`r quantile_0.025_2`, `r quantile_0.975_2`).





